/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIS.h"
#include "SPIS_PVT.h"
#include "Clock.h"
#include "m_miso_pin_aliases.h"
#include "m_miso_pin.h"
#include "m_mosi_pin_aliases.h"
#include "m_mosi_pin.h"
#include "m_sclk_pin_aliases.h"
#include "m_sclk_pin.h"
#include "s_mosi_pin_aliases.h"
#include "s_mosi_pin.h"
#include "s_sclk_pin_aliases.h"
#include "s_sclk_pin.h"
#include "s_ss_pin_aliases.h"
#include "s_ss_pin.h"
#include "s_miso_pin_aliases.h"
#include "s_miso_pin.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "LCD.h"
#include "CS_aliases.h"
#include "CS.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

