# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\jthem\Documents\PSoC Creator\PWMExample01\ADC_SAR_PrISM01.cydsn\ADC_SAR_PrISM01.cyprj
# Date: Fri, 01 Apr 2016 23:45:24 GMT
#set_units -time ns
create_clock -name {ADC_SAR_2_theACLK(routed)} -period 886.79245283018872 -waveform {0 443.396226415094} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 18.867924528301888 -waveform {0 9.43396226415094} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 18.867924528301888 -waveform {0 9.43396226415094} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {ADC_SAR_2_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 47 95} -nominal_period 886.79245283018872 [list [get_pins {ClockBlock/dclk_glb_0}]]


# Component constraints for C:\Users\jthem\Documents\PSoC Creator\PWMExample01\ADC_SAR_PrISM01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\jthem\Documents\PSoC Creator\PWMExample01\ADC_SAR_PrISM01.cydsn\ADC_SAR_PrISM01.cyprj
# Date: Fri, 01 Apr 2016 23:45:09 GMT
