/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "WaveDAC_0_OUT_aliases.h"
#include "WaveDAC_0_OUT.h"
#include "WaveDAC_1.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "WaveDAC_0_Clock.h"
#include "WaveDAC_0.h"
#include "WaveDAC_1_OUT_aliases.h"
#include "WaveDAC_1_OUT.h"
#include "WaveDAC_1_Clock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "WaveDAC_1_Wave1_DMA_dma.h"
#include "WaveDAC_1_Wave2_DMA_dma.h"
#include "WaveDAC_1_IDAC8.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "WaveDAC_0_Wave1_DMA_dma.h"
#include "WaveDAC_0_Wave2_DMA_dma.h"
#include "WaveDAC_0_IDAC8.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

